language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: 
  - pip3 install -r requirements.txt 
  - pip3 install coveralls
# command to run tests
script:
  - ./run_tests.sh
after_success:
  - coveralls
