language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: 
  - pip3 install -r requirements.txt 
# command to run tests
script:
  - python source/application.py cov
after_success:
  - coverage report --omit="source/tests/*" -m --fail-under=35
